trigger:
- master

pool:
  vmImage: 'Windows-2019'

variables:
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: VSBuild@1
  displayName: '构建项目'
  inputs:
    solution: '**\*.sln'
    vsVersion: '16.0'
    configuration: 'release'